<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_11724478-05</name>
   <tag></tag>
   <elementGuidId>d4efb580-f992-473f-8edd-9c26d37d4e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='downshift-:r7b:-item-31']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>31ff65ab-4073-4da1-a552-0331bf3fa38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>11724478-05</value>
      <webElementGuid>6104c272-4fa3-471c-837c-f2611dfd1f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex cursor-pointer items-center rounded-[5px] px-3 py-2 bg-neutral-200</value>
      <webElementGuid>82fd5192-4182-45dc-9394-c7eed7cfeed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06709217-5dda-4495-a58c-402a0c343be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7aa0e37a-8761-4242-8d8b-0d6e6ca40d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downshift-:r7b:-item-31</value>
      <webElementGuid>ccd4e7e1-9e78-48c8-95a4-bf7c0812c09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3f29018e-b1e9-4d5e-a925-52714d419da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ccbfb27-131b-41c2-a9bd-f9ad18e1be29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11724478-05</value>
      <webElementGuid>0c799ea9-243c-4924-a72a-13bad491d3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-:r7b:-item-31&quot;)</value>
      <webElementGuid>1995c1f8-81fc-4c09-b611-50249787fd08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='downshift-:r7b:-item-31']</value>
      <webElementGuid>2b6cd56f-126e-4e29-a3e4-d0555f4c23f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='downshift-:r7b:-menu']/li[32]</value>
      <webElementGuid>3f7fc4bf-4450-4a4f-b4fb-9148b95ecbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packet already exists'])[27]/following::li[1]</value>
      <webElementGuid>97527765-b839-42a4-90aa-a4ebcb6e45e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packet already exists'])[26]/following::li[2]</value>
      <webElementGuid>0838e5e5-0dfc-4309-ae39-5333f1ebac5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packet already exists'])[28]/preceding::li[2]</value>
      <webElementGuid>a3d24947-ee0b-475c-b393-f9b4d7441432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packet already exists'])[29]/preceding::li[3]</value>
      <webElementGuid>499d5c38-68f9-4cf6-8fe3-dec13a841ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[32]</value>
      <webElementGuid>3d0c3b93-59b2-40a8-8693-4475e21363d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'downshift-:r7b:-item-31' and (text() = '11724478-05' or . = '11724478-05')]</value>
      <webElementGuid>8cceab50-9203-427e-8558-3bb3bc05056a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
