<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_COMPLETED_downshift-r6j-input</name>
   <tag></tag>
   <elementGuidId>c6cc426c-9f17-4b4e-a84b-20b6425e1cb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/section/div/form/div[1]/div[1]/table/tbody/tr/td[5]/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e487fceb-4b3d-4b26-b04f-838bdf4eeb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ddc066b-a10c-4c6d-8124-f10120d33b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>3d920013-9233-4a2d-bf9b-be4e316d1eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>62cdbef2-195d-411e-a896-bae801abcc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Completed</value>
      <webElementGuid>faa73a17-6577-4fdf-8a05-da26f8d48a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downshift-:r6j:-input</value>
      <webElementGuid>21061823-5456-4d72-830b-d09566ea5551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select status for undefined</value>
      <webElementGuid>36b87d53-98f0-4014-9e7e-e25eca109c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>downshift-:r6j:-label</value>
      <webElementGuid>dbe5f80b-caae-433c-9d0a-d505d5108d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 bg-transparent px-[10px] py-[5px] outline outline-0 pr-[8px] w-full placeholder:text-neutral-900</value>
      <webElementGuid>2a17e0ba-0ecf-41ae-89e9-95950d9b70c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>downshift-:r6j:-menu</value>
      <webElementGuid>87d586b8-fab5-4da5-a4a6-3c7fdf5ca685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8748bc8e-a66f-4a63-8e27-e6341c68ec03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>5fda607a-3881-4bea-b47f-f9f067c6025a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3dc1d75a-e690-48fa-bcdc-209d55ee597e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>414cd3e1-6d7d-4863-93f1-4bc70fc18d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-:r6j:-input&quot;)</value>
      <webElementGuid>1b2144cf-5c84-48a6-a979-b50d7085280d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='downshift-:r6j:-input']</value>
      <webElementGuid>26835424-fdb7-4137-833e-c89ff0fb4111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='packet-details']/div/div/table/tbody/tr/td[5]/div/div/div/div/input</value>
      <webElementGuid>3120a994-7742-493e-8f58-4a0bd358855f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div/div/input</value>
      <webElementGuid>bcc8cda8-96fb-47b8-8a2d-2d5e2f6cd8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Completed' and @id = 'downshift-:r6j:-input']</value>
      <webElementGuid>b089e49e-c0b1-4ff0-b13d-899d22c1a653</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
