<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Number_contactNumber</name>
   <tag></tag>
   <elementGuidId>3a400922-8e03-4646-8141-7c28ef2d876e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contactNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contactNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>270b5bd3-4d31-4301-afa2-50b4af556f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f12902f-4df3-40fc-8f1d-414947476c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contact Number</value>
      <webElementGuid>47037585-79b8-4f1b-811e-3f07bfc99db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactNumber</value>
      <webElementGuid>918726f2-3aca-4df3-83ad-3b23e3f80a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contactNumber</value>
      <webElementGuid>c903735d-8545-4a87-aaea-e8a62aa47b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded border border-solid !border-[#ecf0f1] !bg-[#F8FAFB] px-3 py-2 disabled:cursor-not-allowed disabled:opacity-40</value>
      <webElementGuid>1b8a7226-d588-4c56-b5d5-1d4480f6569f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactNumber&quot;)</value>
      <webElementGuid>3ac50d2b-b441-4dab-be44-033a9bcc3a60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contactNumber']</value>
      <webElementGuid>d8c6bcec-ddd6-4d1d-84e4-e3a2ce87f6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rp:']/form/div[2]/div/div[4]/input</value>
      <webElementGuid>4add0ecf-6f6d-4d45-9725-2c149d111f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>acc77d8c-c891-40c3-8824-65086e5a3355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Contact Number' and @name = 'contactNumber' and @id = 'contactNumber']</value>
      <webElementGuid>c130cc21-e691-4a77-842b-6a03bf8236f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
