<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_URL Link_urlLink</name>
   <tag></tag>
   <elementGuidId>514c0cb6-daae-460a-a31d-34fc8c22cf23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#urlLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='urlLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64762d71-b6a0-4f32-ae1d-9a6417f97f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74cd777a-7d7e-4e80-b78d-ac95359824b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>URL Link</value>
      <webElementGuid>2f097f0b-a7d3-4aae-983a-07fe09538bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>urlLink</value>
      <webElementGuid>0a68bb24-3d6f-4129-a290-d77b1dc3ade4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>urlLink</value>
      <webElementGuid>dacf8aee-5b29-4a51-8cda-55f2ef2f5c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded border border-solid !border-[#ecf0f1] !bg-[#F8FAFB] px-3 py-2 disabled:cursor-not-allowed disabled:opacity-40</value>
      <webElementGuid>a74367b0-fe93-4d16-9619-8d512cd803c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;urlLink&quot;)</value>
      <webElementGuid>64b63bf6-c380-4ed1-aac4-e9d2fd316e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='urlLink']</value>
      <webElementGuid>dbbf6f8f-0501-433d-93dc-5a26a921f974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rp:']/form/div[2]/div/div[5]/input</value>
      <webElementGuid>813bb303-7c5a-46c9-87fd-2ec4354bcdaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>e0b3a9f1-15c6-45a0-8647-704d91e60c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'URL Link' and @name = 'urlLink' and @id = 'urlLink']</value>
      <webElementGuid>dc3c3a8d-4a4a-4b7e-8859-fcacb75ff9a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
