<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Notes</name>
   <tag></tag>
   <elementGuidId>b27ea44a-6f5d-4f6f-9678-1d68097aed16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-col.col-span-7 > label.mb-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rp:']/form/div[2]/div/div[10]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ae14e5a0-8995-4d3e-863c-dc7616e97310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2</value>
      <webElementGuid>a3723281-f46d-477a-8bf2-c74d74097fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>2d563365-3443-4b06-a6fd-dc794a4a2847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notes:</value>
      <webElementGuid>9262f3a1-418c-4991-8848-862cd60364b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rp:&quot;)/form[@class=&quot;flex flex-col gap-y-0&quot;]/div[@class=&quot;max-h-[calc(100vh-18rem)] overflow-y-scroll&quot;]/div[@class=&quot;grid grid-cols-12 gap-x-6 gap-y-4 !px-5 !pb-5&quot;]/div[@class=&quot;flex flex-col col-span-7&quot;]/label[@class=&quot;mb-2&quot;]</value>
      <webElementGuid>69b00b55-ce5d-4704-bbfb-9591eb4c4657</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rp:']/form/div[2]/div/div[10]/label</value>
      <webElementGuid>b2282251-d9e3-4610-90ca-2ed6b72be81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Time'])[1]/following::label[1]</value>
      <webElementGuid>712a97d0-a517-4847-a872-bdc7aa4d5727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/following::label[2]</value>
      <webElementGuid>f9f43be3-85eb-4a27-984e-72d57d616642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Day'])[1]/preceding::label[2]</value>
      <webElementGuid>f71e525b-d5a5-46f2-9c71-512f5cc84326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::label[3]</value>
      <webElementGuid>b8fb911a-8228-4e8c-8450-e3811b1832d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notes:']/parent::*</value>
      <webElementGuid>6cf9de9c-291f-4eec-ac31-e20df8bac61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/label</value>
      <webElementGuid>80e76130-821e-4661-b136-e5ce18f569dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Notes:' or . = 'Notes:')]</value>
      <webElementGuid>03ba3414-d210-42fd-bb28-2397a6133782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
