<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag and drop or browse from File Manager to upload</name>
   <tag></tag>
   <elementGuidId>2742f9a7-1a40-4285-93a0-ca5ef04f5170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.h-full.flex-col.items-center.justify-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rr:']/form/div[2]/div/div[4]/button/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89d9dc26-1261-4e91-a1cb-96f2591b12c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-full flex-col items-center justify-center</value>
      <webElementGuid>cad1c535-ad7e-4374-9220-81f6d8feee97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag and drop or browse from File Manager to upload</value>
      <webElementGuid>181a7e7f-529b-4164-956d-f440c24e5573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rr:&quot;)/form[@class=&quot;flex flex-col gap-y-0&quot;]/div[@class=&quot;max-h-[calc(100vh-18rem)] overflow-y-scroll&quot;]/div[@class=&quot;grid grid-cols-12 gap-x-6 gap-y-4 !px-5 !pb-5&quot;]/div[@class=&quot;col-span-7 col-start-1&quot;]/button[@class=&quot;relative h-52 w-full rounded !bg-[#F8FAFB]&quot;]/div[@class=&quot;h-52 w-full rounded&quot;]/div[@class=&quot;absolute top-0 left-0 h-full w-full&quot;]/div[@class=&quot;flex h-full flex-col items-center justify-center&quot;]</value>
      <webElementGuid>0310c0e8-065d-4e82-9796-47794953ec2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rr:']/form/div[2]/div/div[4]/button/div/div/div</value>
      <webElementGuid>b4cd0b55-ed0f-4d52-a5ac-07818cfe208c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sequence'])[1]/following::div[4]</value>
      <webElementGuid>f466a8a7-24a2-4e00-9d43-e782df29f103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placement'])[1]/following::div[5]</value>
      <webElementGuid>2f5ba529-10ef-4f9b-96bb-7cdaf0f80b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ad Type'])[1]/preceding::div[2]</value>
      <webElementGuid>a3bb2cd4-e5f1-439d-a199-9dc3a2d5fdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div</value>
      <webElementGuid>df2d3e84-fefa-43fd-97e8-2c7dc610ec27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drag and drop or browse from File Manager to upload' or . = 'Drag and drop or browse from File Manager to upload')]</value>
      <webElementGuid>068c810e-06b5-4e6d-b721-d593d53f243c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
