<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag and drop or browse from File Manag_003297</name>
   <tag></tag>
   <elementGuidId>03adc568-61f7-435e-8d71-24b7415d5c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.h-full.flex-col.items-center.justify-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rr:']/form/div[2]/div/div[4]/button/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9518262-049b-4eb8-9a86-ce1893457689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-full flex-col items-center justify-center</value>
      <webElementGuid>b0cfb1e8-3766-484d-a4a0-c3dd76ee19e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag and drop or browse from File Manager to upload</value>
      <webElementGuid>3942b1c3-9f84-4000-ba33-37b2744cb94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rr:&quot;)/form[@class=&quot;flex flex-col gap-y-0&quot;]/div[@class=&quot;max-h-[calc(100vh-18rem)] overflow-y-scroll&quot;]/div[@class=&quot;grid grid-cols-12 gap-x-6 gap-y-4 !px-5 !pb-5&quot;]/div[@class=&quot;col-span-7 col-start-1&quot;]/button[@class=&quot;relative h-52 w-full rounded !bg-[#F8FAFB]&quot;]/div[@class=&quot;h-52 w-full rounded&quot;]/div[@class=&quot;absolute top-0 left-0 h-full w-full&quot;]/div[@class=&quot;flex h-full flex-col items-center justify-center&quot;]</value>
      <webElementGuid>ff4aa4ee-866f-4b64-adf8-b9e1c5abd8e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rr:']/form/div[2]/div/div[4]/button/div/div/div</value>
      <webElementGuid>704c36c5-cc03-4756-b5fe-3e1776c5c4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sequence'])[1]/following::div[4]</value>
      <webElementGuid>3fd611d6-72d5-4858-a93f-0ee9cc55cad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placement'])[1]/following::div[5]</value>
      <webElementGuid>ca17e0e8-dcbc-4b7f-b59f-d09bc1c8a635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ad Type'])[1]/preceding::div[2]</value>
      <webElementGuid>0ecefe13-02cc-4c8f-bc38-631ebb0db620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div</value>
      <webElementGuid>92616815-1cdd-4247-9d2a-20aaf143178e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drag and drop or browse from File Manager to upload' or . = 'Drag and drop or browse from File Manager to upload')]</value>
      <webElementGuid>ebd6e2d2-db9a-4f8f-b0c9-8e3bf36525ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
