<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sequence_sequence</name>
   <tag></tag>
   <elementGuidId>0d0cbad6-1b86-417f-bdc9-8b2a6f358155</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sequence</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sequence']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62fb696a-716a-492c-9125-0e0f5f671674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c60f5577-a2a9-4355-b0f0-9089e3e3cd34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sequence</value>
      <webElementGuid>4f4c2ed5-845e-4232-923d-2579eb7156c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>caf97c1d-dee5-4d30-8c9e-0f7dfe0f7a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sequence</value>
      <webElementGuid>fa17aed0-6a07-4d6f-8093-9328dbb24c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sequence</value>
      <webElementGuid>7f9c8551-3e32-4aad-9daa-549ed3d6cb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded border border-solid !border-[#ecf0f1] !bg-[#F8FAFB] px-3 py-2 disabled:cursor-not-allowed disabled:opacity-40</value>
      <webElementGuid>419d669d-66f4-4856-b060-7471878f3104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sequence&quot;)</value>
      <webElementGuid>2e7fdd2a-a1ec-4a59-ad43-5d47b1262d7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sequence']</value>
      <webElementGuid>5fc74808-4b12-42a8-add1-b5c209d8e53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rr:']/form/div[2]/div/div[3]/input</value>
      <webElementGuid>82427bb7-55ae-4cdb-9c24-9ceba3352054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6f9f7861-ac0d-4cc4-b71a-f7178bc2d6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Sequence' and @name = 'sequence' and @id = 'sequence']</value>
      <webElementGuid>fa283ef9-a3de-479d-a398-d45abbd7f6d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
