<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Time_startTime</name>
   <tag></tag>
   <elementGuidId>6c4c4666-cf92-451e-9e58-2217467f2b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f5f88c4-1e89-4299-9460-e4976722d6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>89048b5c-cf9e-4277-b084-ee47bb61a197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startTime</value>
      <webElementGuid>2a50e85e-2c75-46bb-9c2b-079031ddb51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startTime</value>
      <webElementGuid>6dff0d07-1321-4f1e-b47d-1128d4faf8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded border border-solid !border-[#ecf0f1] !bg-[#F8FAFB] px-3 py-2 disabled:cursor-not-allowed disabled:opacity-40</value>
      <webElementGuid>bd48d132-c98a-480f-b418-840beae9ffc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startTime&quot;)</value>
      <webElementGuid>9ae8639f-a6d3-44bb-b517-e41916fbce22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startTime']</value>
      <webElementGuid>6c51f52e-370b-4d7c-afae-b8309560975a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rr:']/form/div[2]/div/div[8]/input</value>
      <webElementGuid>61afdf07-0d53-4cc7-9f6f-ec992904d6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>97d80539-e4fd-4ec9-b29c-af8c41c91357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'time' and @name = 'startTime' and @id = 'startTime']</value>
      <webElementGuid>1322cf14-6707-4672-bc39-00a29f6aac91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
