<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Homepage</name>
   <tag></tag>
   <elementGuidId>82f6cb35-6f17-4cb7-9e70-6e163437f3b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#placement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='placement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aa27ade5-aca0-4cec-b377-0d5e69587713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>placement</value>
      <webElementGuid>9a58d442-192c-4fc5-a76a-f86bc89b105a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>placement</value>
      <webElementGuid>3263d0f4-c001-406d-b32a-40432b8de3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded border border-solid !border-[#ecf0f1] !bg-[#F8FAFB] px-3 py-2</value>
      <webElementGuid>037b3408-3809-47db-aaba-7968a50c854f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Homepage</value>
      <webElementGuid>112b3d1f-32a3-4da9-bcd1-c24e8f04d28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;placement&quot;)</value>
      <webElementGuid>5a319190-5dc2-4baa-bf50-b319ba4d6280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='placement']</value>
      <webElementGuid>abd645f7-fc2d-442d-babb-2f701e201eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rr:']/form/div[2]/div/div[2]/select</value>
      <webElementGuid>29af9986-27bb-4ee7-b314-418605240b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placement'])[1]/following::select[1]</value>
      <webElementGuid>951beb5b-2404-41a0-8b8b-3230f00bffa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::select[1]</value>
      <webElementGuid>0c858134-e9fa-475f-8b44-5b7cf592d9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sequence'])[1]/preceding::select[1]</value>
      <webElementGuid>00dabbac-76c2-47ec-8bf9-10fb4572b75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag and drop or browse from File Manager to upload'])[1]/preceding::select[1]</value>
      <webElementGuid>80fa0dbf-4b45-490d-a4db-92eea58bd0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3a58e7c5-6fa2-490b-85e1-8be03d102b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'placement' and @id = 'placement' and (text() = 'Homepage' or . = 'Homepage')]</value>
      <webElementGuid>460fa611-a73f-4d4f-9293-36bce6e434d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
