<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create AnnouncementsTitlePlacementGloba_18da3c</name>
   <tag></tag>
   <elementGuidId>35941696-8356-407b-9221-d57d496dae6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rd:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9fd8234a-6403-45cf-80c5-854cc4a01ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>ad728703-8b67-4d42-a611-f5157c50951f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:rd:</value>
      <webElementGuid>bf6b23a8-3ac2-42cf-bad6-394dad8d436a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>radix-:rf:</value>
      <webElementGuid>c9f208b1-fde7-4175-a17d-13d2b3559f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>radix-:re:</value>
      <webElementGuid>966fb3ed-ed90-433b-ba1b-ffb899cb46c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>5f29fc82-0ca2-4f44-a7cc-e4f4b1a3901d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixed left-[50%] top-[50%] z-50 grid w-full translate-x-[-50%] translate-y-[-50%] gap-4 border bg-white shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg max-w-[min(calc(100vw-2rem),1000px)] !gap-y-0 overflow-hidden p-0</value>
      <webElementGuid>cb048f93-c9f3-4aa1-91e4-1bf39f01121a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>538cf3b9-5497-4d03-a075-8dd38cb36db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create AnnouncementsTitlePlacementGlobalHomepageSettingsAnnouncement Description4/150Contact NumberPhone number must be validURL LinkStart DateStart TimeNotes:All DaySaveClose</value>
      <webElementGuid>292cad50-90be-4f37-a766-4334f82ee97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rd:&quot;)</value>
      <webElementGuid>2effb9c9-c7e4-4668-8a36-29a564c638fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-:rd:']</value>
      <webElementGuid>77a2403b-d7dc-4bab-9975-fdf54dffe4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[10]/following::div[2]</value>
      <webElementGuid>b562f70b-d7f7-4790-bf12-f8652dc064e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>0e3d004a-495a-467d-84f3-992f241eadd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-:rd:' and (text() = 'Create AnnouncementsTitlePlacementGlobalHomepageSettingsAnnouncement Description4/150Contact NumberPhone number must be validURL LinkStart DateStart TimeNotes:All DaySaveClose' or . = 'Create AnnouncementsTitlePlacementGlobalHomepageSettingsAnnouncement Description4/150Contact NumberPhone number must be validURL LinkStart DateStart TimeNotes:All DaySaveClose')]</value>
      <webElementGuid>d0c029ae-9f53-4a8b-b876-006d6f9631d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
