<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_adName</name>
   <tag></tag>
   <elementGuidId>7078aaf8-df3e-4e86-826d-0150bd58d491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='adName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13c50bf6-e3b0-4b6f-b25a-bed09def221f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81d4fbdd-b293-496c-aec8-67c60bf29612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adName</value>
      <webElementGuid>6cecd884-8323-40a8-9ec3-d7dfe69e2f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ad Name</value>
      <webElementGuid>ad5bdc6f-bc18-4027-8040-02b34f6dbb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adName&quot;)</value>
      <webElementGuid>b96311bd-c5a6-4ca1-9712-07cd081523d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='adName']</value>
      <webElementGuid>3d152e47-2f57-46c4-b847-6f3dc0c678d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2h:']/div/div/div/div/input</value>
      <webElementGuid>29acbef5-fb99-4757-a704-8052e90ba382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>64feee52-a569-4ba7-b8e9-dd41c2fa5063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'adName' and @placeholder = 'Ad Name']</value>
      <webElementGuid>c247cf6d-986c-4b31-9905-e68d5b9c47f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
