<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_End Time_slider</name>
   <tag></tag>
   <elementGuidId>8e8b92f2-5473-4eb2-8571-5282096f6494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.slider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r2h:']/div/div/div[3]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a575672-b505-44e9-bf0f-094d8aaa3969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>a47a657f-c0cc-493b-9d66-e2da60db7ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r2h:&quot;)/div[@class=&quot;add-campaign-container&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;all-day-area&quot;]/label[@class=&quot;switch&quot;]/span[@class=&quot;slider&quot;]</value>
      <webElementGuid>3a67fda8-5c0f-4a98-905e-fa2c030e851c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2h:']/div/div/div[3]/label/span</value>
      <webElementGuid>a7a89d67-5330-4aec-a6e6-8eef1757db6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>d704c3f6-4331-4cc4-9ce3-5efcbdc01557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
