<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Test Automation (1)</name>
   <tag></tag>
   <elementGuidId>a22d2726-d213-4528-b551-820070c7f1eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div[2]/div[2]/div/div/div[2]/div[8]/div[2]/div[2]/div[1]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>658355e0-ff8e-485e-9fb7-9d4069b2288e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Automation</value>
      <webElementGuid>e9fab3e6-5c4f-4e1f-b5b4-4f1ed8dbd6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;flex h-full min-h-screen grow flex-col&quot;]/div[@class=&quot;flex size-full grow flex-col&quot;]/div[@class=&quot;w-full px-[30px] py-10&quot;]/div[@class=&quot;rbc-addons-dnd rbc-calendar&quot;]/div[@class=&quot;rbc-month-view&quot;]/div[@class=&quot;rbc-month-row&quot;]/div[@class=&quot;rbc-row-content&quot;]/div[@class=&quot;rbc-addons-dnd-row-body&quot;]/div[@class=&quot;rbc-row&quot;]/div[@class=&quot;rbc-row-segment&quot;]/div[@class=&quot;rbc-event important&quot;]/div[@class=&quot;rbc-addons-dnd-resizable&quot;]/div[@class=&quot;rbc-event-content&quot;]/div[@class=&quot;_container_1ra9z_5&quot;]/span[1]</value>
      <webElementGuid>b77a48ab-5c82-4cbc-825e-478d80c6eec9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div[2]/div[10]/div[2]/div[2]/div/div[3]/div/div/div[2]/div/span</value>
      <webElementGuid>ac61dcf4-37fd-478c-b551-d237584f4e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Automation'])[1]/following::span[1]</value>
      <webElementGuid>34291908-428f-48bb-b90a-33f221eb09f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[3]/following::span[2]</value>
      <webElementGuid>e580dee7-6049-4bc7-9404-1364454111e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='November'])[2]/preceding::span[1]</value>
      <webElementGuid>7c750c53-673a-411c-a0a2-bc79e395dbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/preceding::span[2]</value>
      <webElementGuid>cb661fa7-28a5-45a9-b263-849329947df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[2]/div/div[3]/div/div/div[2]/div/span</value>
      <webElementGuid>23848691-2b41-481c-8964-09ff2dee6f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Test Automation' or . = 'Test Automation')]</value>
      <webElementGuid>7a6b8f92-dcb7-4821-9e41-65571c23334b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
