<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_For Test purpos</name>
   <tag></tag>
   <elementGuidId>8d17286e-17a6-4f77-8440-4591d5d371ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8c1c460c-a418-4e29-ab63-b71c5ed51a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>3180c80c-8b9e-457a-9c5c-a2c9ddee66c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>7ccf0e28-62b0-466b-8be0-758d4e1f304c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>For Test purpos</value>
      <webElementGuid>861dce81-eb51-4329-973f-5ea66b73d96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note&quot;)</value>
      <webElementGuid>f0cd10a8-08de-49d4-a9c9-73c2a45d5fb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='note']</value>
      <webElementGuid>07d3bc36-b65b-4e27-9c61-cc28076b5ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2h:']/div/div/div/div[2]/textarea</value>
      <webElementGuid>b9127725-8881-4096-a13d-cc80faf5bd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::textarea[1]</value>
      <webElementGuid>57ce55b0-3af7-49b7-837d-078361d02021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::textarea[1]</value>
      <webElementGuid>374734b8-d618-4dab-b560-f2cb97392359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placement'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a941f53e-14e2-4fd7-b8d4-d939d8435794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag and drop or click to upload a file'])[1]/preceding::textarea[1]</value>
      <webElementGuid>679d4ba0-9cb8-408b-956b-3731dfc20c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='For Test purpos']/parent::*</value>
      <webElementGuid>4a0c6626-bf0f-412b-8dd5-4adb9cd2e274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3a22edfd-4354-400a-a22e-91fe37cbe5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'note' and @placeholder = 'Notes' and (text() = 'For Test purpos' or . = 'For Test purpos')]</value>
      <webElementGuid>6a69cc6f-94fd-4d76-9102-bfed1610117e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
