<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_For Test p</name>
   <tag></tag>
   <elementGuidId>52ce73e0-c681-45d0-9180-c4f318ce7729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6db6e3c4-d1af-49ad-b83b-022ce17c8a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>3b2250ca-befe-47cd-a908-7d9dddaa59b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>494de201-f265-4917-9ff6-967daa4224e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>For Test p</value>
      <webElementGuid>71ea78ad-da8b-48e3-87b7-7c57eed25ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note&quot;)</value>
      <webElementGuid>0202453d-b500-474a-b516-2d099241caef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='note']</value>
      <webElementGuid>a4a87f2f-7f5e-433a-b59b-616e3f2faf59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2h:']/div/div/div/div[2]/textarea</value>
      <webElementGuid>a61d70c5-57b9-4f13-b766-e6ea8b946812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::textarea[1]</value>
      <webElementGuid>e3def667-d777-4688-bdcb-e2f967d7a606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::textarea[1]</value>
      <webElementGuid>41e70d82-3eac-42c9-bea5-6b8ac1736bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placement'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e5da1a1c-a7b8-4ec1-8a22-460399c13ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag and drop or click to upload a file'])[1]/preceding::textarea[1]</value>
      <webElementGuid>1536921d-8456-49c5-bfaa-d24c66393ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='For Test p']/parent::*</value>
      <webElementGuid>47f1ad7d-7ff4-48e5-a943-273ff7e14099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e1e5507b-8692-49b9-8223-d8767e990636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'note' and @placeholder = 'Notes' and (text() = 'For Test p' or . = 'For Test p')]</value>
      <webElementGuid>ec3615d8-7d84-4cb5-a9cc-211e44c588b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
