<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do this to reduce the number of times_edee07</name>
   <tag></tag>
   <elementGuidId>a8d72982-6f89-441f-bd62-4a7596997583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#KmsiCheckboxField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='KmsiCheckboxField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d6da3dc-07b1-45ef-a8a9-622c17fd2de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>KmsiCheckboxField</value>
      <webElementGuid>fd715d6f-03cf-4080-aacc-155b7cc75efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DontShowAgain</value>
      <webElementGuid>6e5cac58-2a29-44c5-8ebb-3516fd8f1e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>586d865f-322e-4a4c-ab77-a2bddd867042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32835bd6-8ef5-446d-8177-abfd3227e46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>ariaLabel: str['STR_Kmsi_DontShowAgain']</value>
      <webElementGuid>8dc17028-452e-4ff8-8bf8-bb3da2fd0ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Don't show this again</value>
      <webElementGuid>e20d9fef-6a7f-484d-987f-1d714c97a006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KmsiCheckboxField&quot;)</value>
      <webElementGuid>cf957661-c449-4be0-be57-1de338a830c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='KmsiCheckboxField']</value>
      <webElementGuid>78e49db0-6514-44d4-9362-f0fd947de6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox']/div[3]/div/div[2]/div/div[3]/div/div/label/input</value>
      <webElementGuid>2b820268-2fd1-4022-ab88-1df5555cc76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>bd128af5-b8ca-47d9-92d8-80f785db6e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'KmsiCheckboxField' and @name = 'DontShowAgain' and @type = 'checkbox']</value>
      <webElementGuid>603c73cf-4802-46f8-8af4-25fb20785850</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
