<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do this to reduce the number of times_edee07</name>
   <tag></tag>
   <elementGuidId>cd566186-e825-4e66-85f0-07f413942e88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#KmsiCheckboxField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='KmsiCheckboxField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acf21dc3-5cf2-47f7-be99-c61566938706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>KmsiCheckboxField</value>
      <webElementGuid>df568186-cc81-46c8-8fe3-042338653cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DontShowAgain</value>
      <webElementGuid>84c829fd-01c7-4df8-baeb-4d6ad616b69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6e609faa-971a-4326-bc1e-522fcc8de31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>872366cc-48dd-4cbf-8d0a-edc6e49aa92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>ariaLabel: str['STR_Kmsi_DontShowAgain']</value>
      <webElementGuid>80d72a19-a9dd-4c17-bc12-cc2c5e876679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Don't show this again</value>
      <webElementGuid>50ebb46d-b2bb-459d-a967-8ffe372ebfa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KmsiCheckboxField&quot;)</value>
      <webElementGuid>ac57b833-3404-404f-a76f-75c9c03ac021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='KmsiCheckboxField']</value>
      <webElementGuid>6ac9f439-a7ba-4957-8f4c-9951ca0a5cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox']/div[3]/div/div[2]/div/div[3]/div/div/label/input</value>
      <webElementGuid>3f818200-103b-441e-ab5b-41be0030b0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>249e6477-f8a3-45cb-b608-15e8cd020c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'KmsiCheckboxField' and @name = 'DontShowAgain' and @type = 'checkbox']</value>
      <webElementGuid>ac389b0c-185a-4adb-a7e4-cfd05dffcb24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
