<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_From computer</name>
   <tag></tag>
   <elementGuidId>04e34e5c-7be6-4ede-a7fb-b1121a17ac02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[24]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75e855bc-5264-4d78-a55e-6734d9733351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c417b9dd-2905-46b5-8376-aa08ec4df7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group flex select-none items-center justify-center text-nowrap rounded-[8px] border border-solid border-[--color] text-center outline-none transition ease-in-out focus:border-[--dark-color] focus:shadow-[0_0_0_3px] [--color:theme(colors.neutral.main)] [--dark-color:theme(colors.neutral.dark)] focus:shadow-neutral-main/40 bg-transparent hover:border-[--color] hover:bg-[--color] focus:text-[--dark-color] active:bg-[--dark-color] active:text-white hover-unfocus:text-white px-[8px] font-normal focus:bg-neutral-dark/20 py-[5px] text-blue-600</value>
      <webElementGuid>4806c23b-eb27-45fd-a9ff-5096a6354652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>460c9336-8a8d-4bc0-a96a-827dbaee8941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb226533-c033-4b78-9d2a-1c39c18b13fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From computer</value>
      <webElementGuid>093bea54-ff7b-4716-abfb-369d3f8c26e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;fixed inset-0 z-[100000] flex min-h-full items-center justify-center overflow-y-auto bg-black/60 p-4 text-center&quot;]/div[@class=&quot;flex size-full w-full overflow-hidden rounded-[15px] bg-white p-[12px] text-left align-middle shadow-xl outline-none h-full max-w-[1350px] md:max-h-[85vh]&quot;]/section[@class=&quot;flex size-full flex-col outline-none&quot;]/div[@class=&quot;flex size-full flex-col overflow-y-hidden&quot;]/div[@class=&quot;flex h-full flex-1 py-[5px]&quot;]/div[@class=&quot;flex h-full flex-1 flex-col items-center justify-center space-y-3 rounded-[5px] py-3&quot;]/div[@class=&quot;flex flex-col space-x-0 space-y-2 md:flex-row md:space-x-2 md:space-y-0&quot;]/button[@class=&quot;group flex select-none items-center justify-center text-nowrap rounded-[8px] border border-solid border-[--color] text-center outline-none transition ease-in-out focus:border-[--dark-color] focus:shadow-[0_0_0_3px] [--color:theme(colors.neutral.main)] [--dark-color:theme(colors.neutral.dark)] focus:shadow-neutral-main/40 bg-transparent hover:border-[--color] hover:bg-[--color] focus:text-[--dark-color] active:bg-[--dark-color] active:text-white hover-unfocus:text-white px-[8px] font-normal focus:bg-neutral-dark/20 py-[5px] text-blue-600&quot;]</value>
      <webElementGuid>818a9b61-2baf-4389-9e16-c0fa229e900b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[24]</value>
      <webElementGuid>c71612fb-f5aa-43eb-bd17-200a1251d1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From drafts'])[1]/following::button[1]</value>
      <webElementGuid>0bb9a5a9-5d94-40d9-b1ee-40fc5e46569d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add HEAT'])[2]/following::button[5]</value>
      <webElementGuid>14b9cffa-719b-46ea-ab71-a408cd84d9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>fd0b2d33-c3c4-4857-9a0a-bf189ae774ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[2]/preceding::button[2]</value>
      <webElementGuid>8695bd21-df9e-467a-923c-c5fcdb4dcdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='From computer']/parent::*</value>
      <webElementGuid>dacc7272-968a-4d73-8ed5-2e52e917e6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button[2]</value>
      <webElementGuid>8ac6a1fb-bcca-4300-967a-255a7a68f225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'From computer' or . = 'From computer')]</value>
      <webElementGuid>6481ff9b-50f1-42e3-a772-cb7b806a9254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
