<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>4df47ae9-b7e0-4251-b8f3-ccac8e2e8014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d415a51b-4fa6-4555-8451-e0c208e3ba7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>packet-details</value>
      <webElementGuid>9189672e-9cee-4d0b-8fe6-847d80f8f10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0e4957f0-0910-45ce-bb67-4c6a521c0484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group flex select-none items-center justify-center text-nowrap border border-solid border-[--color] text-center font-bold outline-none transition ease-in-out focus:border-[--dark-color] focus:shadow-[0_0_0_3px] [--color:theme(colors.navy.main)] [--dark-color:theme(colors.navy.dark)] focus:shadow-navy-main/40 bg-[--color] text-white hover:border-[--dark-color] hover:bg-[--dark-color] focus:bg-[--dark-color] data-[selected=&quot;true&quot;]:border-[--dark-color] data-[selected=&quot;true&quot;]:bg-[--dark-color] px-[16px] rounded-[5px] py-[5px]</value>
      <webElementGuid>b0117038-434d-4f8a-b4e4-31fe9909e428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>532a16fe-e3ce-49fc-aa38-533255b97edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5fea0a34-3bae-4054-86c8-97f5595e71a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>71abcb5f-70a2-4419-a965-9ae1b5b8b59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;fixed inset-0 z-[100000] flex min-h-full items-center justify-center overflow-y-auto bg-black/60 p-4 text-center&quot;]/div[@class=&quot;flex size-full w-full overflow-hidden rounded-[15px] bg-white p-[12px] text-left align-middle shadow-xl outline-none h-full max-w-[1350px] md:max-h-[85vh]&quot;]/section[@class=&quot;flex size-full flex-col outline-none&quot;]/div[@class=&quot;flex size-full flex-col overflow-y-hidden&quot;]/div[@class=&quot;flex w-full justify-evenly justify-self-end rounded-[8px] border border-neutral-400 p-[5px] shadow&quot;]/div[@class=&quot;flex w-full flex-col justify-end space-x-0 space-y-3 md:flex-row md:space-x-[5px] md:space-y-0&quot;]/button[@class=&quot;group flex select-none items-center justify-center text-nowrap border border-solid border-[--color] text-center font-bold outline-none transition ease-in-out focus:border-[--dark-color] focus:shadow-[0_0_0_3px] [--color:theme(colors.navy.main)] [--dark-color:theme(colors.navy.dark)] focus:shadow-navy-main/40 bg-[--color] text-white hover:border-[--dark-color] hover:bg-[--dark-color] focus:bg-[--dark-color] data-[selected=&quot;true&quot;]:border-[--dark-color] data-[selected=&quot;true&quot;]:bg-[--dark-color] px-[16px] rounded-[5px] py-[5px]&quot;]</value>
      <webElementGuid>2caa228f-cd86-47d3-9ee6-50c3fda7f410</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>8e98b5f1-dad9-4294-91f1-cb2eaa1a7e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save as draft'])[1]/following::button[1]</value>
      <webElementGuid>d38b17a4-31ef-4ea2-8a96-aae20aabb4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[2]</value>
      <webElementGuid>2866676b-d33c-4c43-a05a-82d7d447919f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>ab310973-6f91-4943-a191-ade520eb7fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button[2]</value>
      <webElementGuid>b6a3bd6a-7461-4507-a7a3-7cd01f103a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@form = 'packet-details' and @type = 'submit' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>49dfba78-4430-4e49-961a-0dd37474fe51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
