<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Completed_react-aria148752833-r5h</name>
   <tag></tag>
   <elementGuidId>4fb40cfc-fc27-4e44-892f-46a3356437aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/section/div/form/div[2]/div[1]/div/div[4]/div[2]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53e5c0e6-e84a-48d0-bf98-a9849638ebb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb3a83b4-4b9f-4457-a0cf-eacd94eec32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>PO #</value>
      <webElementGuid>49013169-063d-432a-8418-daf679bf9fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria148752833-:r5h:</value>
      <webElementGuid>e010f934-7fe3-4647-9c39-032a3b0da609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>PO #</value>
      <webElementGuid>33855543-01c2-48ee-9628-dd1fbbc86522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex-1 bg-transparent px-[10px] py-[5px] outline outline-0 placeholder:text-neutral-500</value>
      <webElementGuid>c2178939-0c53-497a-9db5-ed7b95da32ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d86cf55-e4d6-4382-ba80-982cbda9fd53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria148752833-:r5h:&quot;)</value>
      <webElementGuid>cace89d1-0596-4b07-ae09-fbd5aaef6ea2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='react-aria148752833-:r5h:']</value>
      <webElementGuid>45d7f659-edfa-4b04-ad0c-0c01eb9e4ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='packet-details']/div[2]/div/div/div[4]/div[2]/div/input</value>
      <webElementGuid>46b9acda-f9f8-44de-8007-2ac686b2dca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>d261bc87-ba1f-4367-90df-98a470dcc0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'PO #' and @id = 'react-aria148752833-:r5h:']</value>
      <webElementGuid>3eeafff7-33b8-48f9-b497-6c234dca5f76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
