<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Completed_react-aria1660808483-r4j</name>
   <tag></tag>
   <elementGuidId>b5a63717-1ce7-4b4b-a393-3ae12d5aedc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='react-aria1660808483-:r4j:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1f768ea-bd86-49db-b937-67c95ccd93ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53ea8883-9456-4d1c-a5d5-3e72a7a71864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Heat #</value>
      <webElementGuid>6bf8a3d9-6dfd-4be2-ae12-3fd2af6d9985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria1660808483-:r4j:</value>
      <webElementGuid>1393108d-b986-4948-9cea-fcf1d9535ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Heat #</value>
      <webElementGuid>a51580a3-0778-4406-9276-db4e15cef7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex-1 bg-transparent px-[10px] py-[5px] outline outline-0 placeholder:text-neutral-500</value>
      <webElementGuid>8937b521-13e9-4c5c-9330-539c7daa6093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5016094-55a5-4b33-b240-2d8c056b3bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria1660808483-:r4j:&quot;)</value>
      <webElementGuid>722c87eb-4b73-4ef9-a7d4-37816566a948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='react-aria1660808483-:r4j:']</value>
      <webElementGuid>321ee157-27d2-4df2-b040-5f941a75dfae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='packet-details']/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>a0c1f3ed-1259-4802-baad-0c4be9bbb082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/input</value>
      <webElementGuid>08c5eda5-ff55-40cf-896c-a9d3a5df4076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Heat #' and @id = 'react-aria1660808483-:r4j:']</value>
      <webElementGuid>28e38d3f-a9ce-4708-a622-45b0e5b837de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
