<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_30281300-00</name>
   <tag></tag>
   <elementGuidId>cd3d1e52-c1c4-42b9-b04a-daf05396a0b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-col > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='downshift-:r6v:-item-0']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>64030230-aa61-4a9a-b42a-ae47eb7e188c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30281300-00</value>
      <webElementGuid>56298b5f-8861-4e6a-99bf-f268a45a7f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-:r6v:-item-0&quot;)/div[@class=&quot;flex flex-col&quot;]/span[1]</value>
      <webElementGuid>7e5effc8-3e2c-493d-aa56-8baece96949a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='downshift-:r6v:-item-0']/div/span</value>
      <webElementGuid>49d84eb4-4bd2-4b0b-b509-b9c6c9212e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::span[3]</value>
      <webElementGuid>c9b6efef-b95c-4c43-8148-ae6f5f4dfc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save as draft'])[1]/following::span[3]</value>
      <webElementGuid>848054d1-9cf9-464f-8654-43a68fb19041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30281300-00']/parent::*</value>
      <webElementGuid>3e29d58b-18ac-4e50-8baa-0a2462eb34ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/span</value>
      <webElementGuid>b20ff1b1-7ae6-4eeb-bfc0-72112b87d43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '30281300-00' or . = '30281300-00')]</value>
      <webElementGuid>0b187475-77a7-4533-85bb-52f77b615bc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
