<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>c7afa552-285b-4dfc-9165-4659faf6260d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div[2]/div/div/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5448e33-9af8-4150-b6b2-76fc83b6500e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd2482fc-fece-4346-9239-d7bf84156260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group flex select-none items-center justify-center text-nowrap rounded-[8px] border border-solid border-[--color] text-center outline-none transition ease-in-out focus:border-[--dark-color] focus:shadow-[0_0_0_3px] [--color:theme(colors.navy.main)] [--dark-color:theme(colors.navy.dark)] focus:shadow-navy-main/40 bg-[--color] text-white hover:border-[--dark-color] hover:bg-[--dark-color] focus:bg-[--dark-color] data-[selected=&quot;true&quot;]:border-[--dark-color] data-[selected=&quot;true&quot;]:bg-[--dark-color] px-[8px] py-[3px] font-normal</value>
      <webElementGuid>7ac58415-c8c0-49e9-96ad-b527dd27b79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3206febc-b563-47d5-9802-09fd9765ae3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cf9c034e-1e5d-4f80-ae1c-d60d3d3bcce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>d1316f30-e084-41ec-86f8-450636b77161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex size-full min-h-screen flex-col bg-neutral-100&quot;]/div[@class=&quot;flex flex-1 flex-col items-stretch justify-center md:flex-row&quot;]/div[@class=&quot;flex w-full max-w-[1650px] flex-1 flex-col px-[10px] py-[30px]&quot;]/div[@class=&quot;mt-6 w-full overflow-x-auto rounded-2xl border bg-white px-[20px] py-6 shadow&quot;]/div[@class=&quot;flex w-full flex-row items-center justify-center space-x-3 mt-3 px-[30px]&quot;]/button[@class=&quot;group flex select-none items-center justify-center text-nowrap rounded-[8px] border border-solid border-[--color] text-center outline-none transition ease-in-out focus:border-[--dark-color] focus:shadow-[0_0_0_3px] [--color:theme(colors.navy.main)] [--dark-color:theme(colors.navy.dark)] focus:shadow-navy-main/40 bg-[--color] text-white hover:border-[--dark-color] hover:bg-[--dark-color] focus:bg-[--dark-color] data-[selected=&quot;true&quot;]:border-[--dark-color] data-[selected=&quot;true&quot;]:bg-[--dark-color] px-[8px] py-[3px] font-normal&quot;]</value>
      <webElementGuid>518461dd-376d-4b9b-bb52-f8b3a6097b6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>2e137db8-6095-4099-8d44-7e5ef03056c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>aa667043-09a8-4dda-a180-444883b15ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::button[1]</value>
      <webElementGuid>7d9d2ab2-face-4324-b721-99fb0cb0f896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>9324acc7-1c46-4954-accf-e0f6f763250e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>47013a49-e2c5-4510-8505-75def1255449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>30cc9596-5713-4bca-be92-bf3205cae4b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
