<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_GlobalHomepageSettings</name>
   <tag></tag>
   <elementGuidId>93165e03-fffc-4ba8-8a7a-dd648c73a3f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#placement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:rd:']/form/div[2]/div/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fc49667c-18c0-4aaa-b74d-e6ec4e597a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>placement</value>
      <webElementGuid>1afc5e4b-caa2-4383-ad1b-3dade8414f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>placement</value>
      <webElementGuid>62bf1344-96fd-4415-afa7-4aa56154c8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded border border-solid !border-[#ecf0f1] !bg-[#F8FAFB] px-3 py-2</value>
      <webElementGuid>29b86c3c-a571-4e8f-acce-afff229841ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GlobalHomepageSettings</value>
      <webElementGuid>85bac0d9-e607-482e-a751-42b26c2452f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;placement&quot;)</value>
      <webElementGuid>fd490270-a1a7-4f56-a336-a13b2964a18a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='placement']</value>
      <webElementGuid>ee4a0477-6d5f-4906-ba98-7ac37ecf2699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rd:']/form/div[2]/div/div[2]/select</value>
      <webElementGuid>7a9518af-7317-4631-8311-f209f7c56a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placement'])[1]/following::select[1]</value>
      <webElementGuid>8211ce8d-7e24-4245-8997-c28522155dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::select[1]</value>
      <webElementGuid>e858ee51-0acd-492d-b6e1-ef8d7acb1589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Announcement Description'])[1]/preceding::select[1]</value>
      <webElementGuid>08401f78-b2d8-4776-9530-cddb1f6cbb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Number'])[1]/preceding::select[1]</value>
      <webElementGuid>fb37e0cc-640a-4bb1-9acb-02b3f4f3de79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>eab21b66-a104-4cb3-9a74-a9a9ce92fc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'placement' and @id = 'placement' and (text() = 'GlobalHomepageSettings' or . = 'GlobalHomepageSettings')]</value>
      <webElementGuid>6e0807e1-d11b-4765-b480-2374ffb49202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
