<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sequence_sequence</name>
   <tag></tag>
   <elementGuidId>dc274a02-68cd-40f8-b216-389aa377dc3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sequence</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sequence']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8e6b70c-5fb5-4f56-ab74-48bb658bfc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c954b850-ddf4-4c76-a7ab-01b260ffe638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sequence</value>
      <webElementGuid>355b012c-d0dc-4486-ac61-6dc91bcb5102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f33cf9d4-294c-4073-9d03-e063a50fe68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sequence</value>
      <webElementGuid>97499169-b5b9-4979-b1df-73aa058ddba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sequence</value>
      <webElementGuid>23f0842f-37ac-4245-bb77-2573bee5d375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded border border-solid !border-[#ecf0f1] !bg-[#F8FAFB] px-3 py-2 disabled:cursor-not-allowed disabled:opacity-40</value>
      <webElementGuid>53b6f15c-fdd5-4c61-a803-bc58a4bd37d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sequence&quot;)</value>
      <webElementGuid>ee3c6945-0fa1-43a0-8913-47bf7c1d2c16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sequence']</value>
      <webElementGuid>320cbd54-d400-4112-98dc-15281e1a59cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rp:']/form/div[2]/div/div[3]/input</value>
      <webElementGuid>c01a5e70-873e-4ef9-9d92-35453447c092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>fa843346-f65c-4ed6-a635-b9a0216473d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Sequence' and @name = 'sequence' and @id = 'sequence']</value>
      <webElementGuid>9c44712d-4666-4389-bfb8-c4fa40ea430f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
