<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Time_endTime</name>
   <tag></tag>
   <elementGuidId>d942452c-64a7-4e64-aec1-abf4d04c666b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48421652-0fbe-4b48-83ff-d650dc04460e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>94fb3fd3-4644-41ad-96f8-e99b6f4bf29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>endTime</value>
      <webElementGuid>f9f1f7ae-2415-40a5-88b5-524dfcd4c77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endTime</value>
      <webElementGuid>77ac1cb5-1108-4797-af4e-c7e2a7c7b872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded border border-solid !border-[#ecf0f1] !bg-[#F8FAFB] px-3 py-2 disabled:cursor-not-allowed disabled:opacity-40</value>
      <webElementGuid>3e3a9b89-fe9b-45c5-82a0-43a0308fa81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endTime&quot;)</value>
      <webElementGuid>fe603f7b-8d3f-435e-8771-392923775519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endTime']</value>
      <webElementGuid>0dfda61e-9aa7-486d-b1e3-5d42ad157339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rp:']/form/div[2]/div/div[10]/input</value>
      <webElementGuid>6bfd5f2e-0f81-4d22-9e0b-e0d9a044c8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>01b08863-e149-4cf9-8a0c-d068afedaeb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'time' and @name = 'endTime' and @id = 'endTime']</value>
      <webElementGuid>51896a3b-e4fa-4b79-b8b6-4391ccc7e9ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
