<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Open_1</name>
   <tag></tag>
   <elementGuidId>d2b254a0-9c66-4bbd-a011-12740ba883a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f2ec5ca-a3fe-4457-a6fb-5888c83abf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>d0e6c0f2-02fa-48e0-9437-5f91a4705658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9ab2fcd3-019e-4ae2-a4e6-b3799ac2cc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>react-aria-1</value>
      <webElementGuid>49a21588-6906-4b5e-ada7-df62d4272075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex min-w-fit flex-1 cursor-pointer select-none space-x-[18px] rounded-[5px] px-[12px] py-[10px] outline-none bg-blue-500/10</value>
      <webElementGuid>b118669a-315d-4fce-b3ec-c927dbfce2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c6c8fa9-f479-4fb3-9a7b-f3dab83d4f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open</value>
      <webElementGuid>b0611669-a122-4b8b-8e02-e4e7ae9f2091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;group rounded-[8px] border border-black/10 bg-white bg-clip-padding text-slate-700 shadow-lg&quot;]/div[@class=&quot;flex flex-col p-[6px] min-w-[170px] py-[5px] outline-none&quot;]/div[@class=&quot;flex min-w-fit flex-1 cursor-pointer select-none space-x-[18px] rounded-[5px] px-[12px] py-[10px] outline-none bg-blue-500/10&quot;]</value>
      <webElementGuid>29b018e3-6829-4cd6-b8cd-06e2ce31db69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::div[5]</value>
      <webElementGuid>83dcf4e4-f90f-434e-9d0c-0394218452b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan'])[1]/following::div[5]</value>
      <webElementGuid>b8808121-8e07-40c7-b3db-ea47746f7936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add HEAT'])[2]/preceding::div[4]</value>
      <webElementGuid>de319e91-1d31-439b-ab63-ce4813720200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/preceding::div[5]</value>
      <webElementGuid>383782a1-b4f9-4f3a-a99a-346c17f63ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div</value>
      <webElementGuid>d3194ab4-ca3d-4316-9e4b-82213c0bdcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Open' or . = 'Open')]</value>
      <webElementGuid>bed9be1f-ec11-40b9-b49d-fdff0b991ee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
