<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Page_react-aria1827729712-ri5</name>
   <tag></tag>
   <elementGuidId>6eadbade-e392-49b8-9553-2d2ab6577194</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div/section/div/form/div[2]/div[1]/div/div[3]/div[2]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d26ea64b-79e3-454d-a1e2-03728589e050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c15f2587-a48e-4e1b-9d8c-d3f27dd0ace7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>0866ad04-9ba7-460b-b519-ce6b7a9446e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria1827729712-:ri5:</value>
      <webElementGuid>876a6430-4ce9-480b-ba2e-eefbbf6300fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>5b619083-c490-486e-9da4-462ccec39ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex-1 bg-transparent px-[10px] py-[5px] outline outline-0 placeholder:text-neutral-500</value>
      <webElementGuid>7a5a78c4-a280-418f-9aa9-f251176725dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>08e25ebb-8f20-407a-b817-bbbc74885ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c38d1488-8063-4516-b18d-db655b526b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8448aa21-5450-4fbd-8cfd-74a7e4eee56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria1827729712-:ri5:&quot;)</value>
      <webElementGuid>43235c2b-7da6-4efa-91c6-c0eb0c873ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='react-aria1827729712-:ri5:']</value>
      <webElementGuid>4449de9e-b3a9-481e-8c55-5ae830ad447b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='packet-details']/div[2]/div/div/div[3]/div[2]/div/input</value>
      <webElementGuid>0c4de2cd-e06a-4d22-8ff6-afe2de06b65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>9370ed58-91ce-4950-915a-11a391dbeaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Description' and @id = 'react-aria1827729712-:ri5:']</value>
      <webElementGuid>9c446617-a005-4fa8-a401-b1a0048cf031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
