<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Sales Packets_lucide lucide-ellipsis</name>
   <tag></tag>
   <elementGuidId>6df7e1d5-17dd-4eed-a871-5505e9ff9722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Packets'])[2]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>ebdcd724-b4a8-4831-997b-8628865785f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>94d87751-5222-4c4e-b473-60019ff6502a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>7bf0b32d-eccb-4445-a129-4daf52cc9ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>732e1d37-b585-43ef-b1a3-79a6ffbfb1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>efe2a5ca-8928-434d-9fd4-23f3f746615d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e36c96ef-5cc4-47de-904e-44fd401f0869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>8beeda6d-1747-4e4b-8f97-736ff1a40784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0f49abc8-2472-474d-9561-a4f6574d79dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>9adf18c8-6344-4d2c-ad92-9b7204e3c71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>a1e466f9-4717-4e8e-9453-1ca7365eddce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lucide lucide-ellipsis</value>
      <webElementGuid>4369de72-31a1-4ea1-8a10-5c1c6d09ee70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria1827729712-:r4p:&quot;)/label[@class=&quot;react-aria-Checkbox&quot;]/div[@class=&quot;w-full rounded-[8px] border border-neutral-200 bg-white p-[10px] shadow-lg transition hover:border-neutral-500&quot;]/div[@class=&quot;flex flex-row justify-between&quot;]/button[@class=&quot;group flex select-none items-center justify-center text-nowrap rounded-[8px] border border-solid text-center outline-none transition ease-in-out focus:shadow-[0_0_0_3px] [--color:theme(colors.blue.600)] [--dark-color:theme(colors.blue.800)] focus:shadow-blue-600/40 border-transparent focus:border-transparent focus:text-[--dark-color] font-normal data-[pressed]:bg-blue-800/20 hocus:bg-blue-800/20 p-[3px] text-blue-600&quot;]/svg[@class=&quot;lucide lucide-ellipsis&quot;]</value>
      <webElementGuid>470606c9-172a-4d33-b83b-a5ecaa99202f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Packets'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>79973630-1ef0-44c5-ad9f-019bcfefea51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HEAT'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>17b39e4d-2d8b-4bc4-850b-1a5b07fa724e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>db4c3b08-5b64-4069-a715-314a665ea108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[2]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>87db7070-145e-4832-a735-117073e4601e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
