<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Completed</name>
   <tag></tag>
   <elementGuidId>e7cd6c17-e44d-4963-a7e3-0be140dcae90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='downshift-:r5v:-item-3']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d662a998-1aac-49f1-8f7c-a97920c18df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completed</value>
      <webElementGuid>a022dc89-e4e8-4676-a5f1-840fdcb00580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-:r5v:-item-3&quot;)/div[@class=&quot;flex flex-col&quot;]/span[1]</value>
      <webElementGuid>ebe54fd2-2efd-4991-bb5c-7aca29ceeab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='downshift-:r5v:-item-3']/div/span</value>
      <webElementGuid>7bc5f6af-5d10-445e-8c73-9d0c7d3aa9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting for vendor'])[1]/following::span[1]</value>
      <webElementGuid>2cbf55a3-9290-4a31-8a86-6f9d08de7ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backordered'])[1]/following::span[2]</value>
      <webElementGuid>99c0c304-a0c1-4fa9-a611-8cb3d3ed9633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Completed']/parent::*</value>
      <webElementGuid>8cb03958-2540-402b-b7b4-7ba085112c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/span</value>
      <webElementGuid>f3aa736e-5926-4fbb-a604-854a56228c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Completed' or . = 'Completed')]</value>
      <webElementGuid>679dd0c0-d702-44d7-a127-48d7750d0e43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
