<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lhander Pangan_grafana-iframe</name>
   <tag></tag>
   <elementGuidId>ea0abb74-1162-4f90-a6ba-283b164565d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.grafana-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>71d65237-0844-414d-a005-85707ca1dc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grafana-iframe</value>
      <webElementGuid>5ecfaa04-355a-49fe-8b33-42be0b4f7c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Grafana Dashboard</value>
      <webElementGuid>a1e5fcc5-9838-4bdb-97e7-888921768fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>aacb5728-c164-4fdb-966d-232d00fbd492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c5273d77-2645-4c19-aa91-c105afa43704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://display.prod.porterpipe.com/d/a6c9d560-ec29-4c54-872b-cf164f310b5d/marketing-dashboard?orgId=1&amp;from=now-7d&amp;to=now&amp;kiosk&amp;theme=light</value>
      <webElementGuid>35965ac0-1957-422b-9dd8-286535a60a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7ae72376-d252-42b8-94a5-e4e6e20a0094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;flex h-full min-h-screen grow flex-col&quot;]/div[@class=&quot;flex size-full grow flex-col&quot;]/div[@class=&quot;flex h-[calc(100vh-65px)] w-full flex-1&quot;]/iframe[@class=&quot;grafana-iframe&quot;]</value>
      <webElementGuid>a52fa56c-e68e-4f46-ac9a-a6189290cc74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/iframe</value>
      <webElementGuid>ba0cb479-e6e7-4195-b894-ee5c6ae62f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c87fcdfa-1837-41cd-899d-b816d220aa7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Grafana Dashboard' and @src = 'https://display.prod.porterpipe.com/d/a6c9d560-ec29-4c54-872b-cf164f310b5d/marketing-dashboard?orgId=1&amp;from=now-7d&amp;to=now&amp;kiosk&amp;theme=light']</value>
      <webElementGuid>f877664b-6306-490b-94b2-ccbd42cd0e0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
