<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sales Packets</name>
   <tag></tag>
   <elementGuidId>012b1feb-f178-4bb1-bdb9-c89e59ef72fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09be4b81-49ef-41ef-8f72-38f0f7ed9d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74a1c364-23d4-462b-929a-db4f15d9cda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group flex select-none items-center justify-center text-nowrap border border-solid text-center outline-none transition ease-in-out focus:shadow-[0_0_0_3px] [--color:theme(colors.navy.main)] [--dark-color:theme(colors.navy.dark)] focus:shadow-navy-main/40 border-transparent focus:border-transparent px-[8px] py-[3px] font-normal data-[pressed]:bg-navy-dark/20 hocus:bg-navy-dark/20 rounded-[5px] text-white focus:text-white</value>
      <webElementGuid>60ba0feb-3658-4954-9b91-64fe915be356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>665abf80-cf79-4bbe-8eef-b6be14e33351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales Packets</value>
      <webElementGuid>de121cc0-6a54-4d48-911f-54fdb7e45a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex size-full min-h-screen flex-col bg-neutral-100&quot;]/div[@class=&quot;flex flex-col items-center justify-center bg-navy-main md:flex-row&quot;]/div[@class=&quot;flex w-full max-w-[1650px] items-center justify-between space-x-6 px-[10px] py-[12px]&quot;]/div[@class=&quot;flex flex-row space-x-6&quot;]/button[@class=&quot;group flex select-none items-center justify-center text-nowrap border border-solid text-center outline-none transition ease-in-out focus:shadow-[0_0_0_3px] [--color:theme(colors.navy.main)] [--dark-color:theme(colors.navy.dark)] focus:shadow-navy-main/40 border-transparent focus:border-transparent px-[8px] py-[3px] font-normal data-[pressed]:bg-navy-dark/20 hocus:bg-navy-dark/20 rounded-[5px] text-white focus:text-white&quot;]</value>
      <webElementGuid>3c76a9a0-ce41-4c37-aa57-2d7f27997d95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>854297d6-f759-44ae-bc33-b14c82b91ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/button[3]</value>
      <webElementGuid>540dd38c-8e2c-4fc7-9da9-555e4597dbd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Packets'])[1]/following::button[1]</value>
      <webElementGuid>164c4e76-4329-413a-86fe-1345de96d7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marben Dimson'])[1]/preceding::button[1]</value>
      <webElementGuid>7533ce54-5cd6-447d-9bf5-4f863a95062e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::button[4]</value>
      <webElementGuid>b19fe623-9251-4334-9e92-8c8cb736115e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sales Packets']/parent::*</value>
      <webElementGuid>f979a640-e2e7-4aa0-bcc3-4719c43a7cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>7bdbe827-9b9c-4b07-a298-b6f0f151238b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Sales Packets' or . = 'Sales Packets')]</value>
      <webElementGuid>4d1eb0f1-7d51-4c8e-bc9d-01781f0c8783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
