<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_12745526-00</name>
   <tag></tag>
   <elementGuidId>1283e69b-bbed-46bf-b8ac-c11dcfeb3e19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='downshift-:r4l:-item-6']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bbc2c76f-8347-4344-8103-133019fcff8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12745526-00</value>
      <webElementGuid>ea8a0b30-c0f5-42a7-a94e-16304994bc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-:r4l:-item-6&quot;)/div[@class=&quot;flex flex-col&quot;]/span[1]</value>
      <webElementGuid>67665109-a84f-4c66-945e-219d9791ca81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='downshift-:r4l:-item-6']/div/span</value>
      <webElementGuid>4eda9c23-fb77-4e25-b5c9-3c6fedb9baaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[2]/following::span[9]</value>
      <webElementGuid>2893fd64-891b-45f4-8ae0-42ec9f70af56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/span</value>
      <webElementGuid>57b60e90-21bd-43cd-8699-b235f4404920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '12745526-00' or . = '12745526-00')]</value>
      <webElementGuid>f1db90b0-18f6-41ff-a71d-95c8ce7d81b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
