<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do this to reduce the number of times_edee07</name>
   <tag></tag>
   <elementGuidId>30281edc-a606-48be-b5b3-8aabe74a590b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#KmsiCheckboxField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='KmsiCheckboxField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f5ba99e-6c27-47b0-80e4-b6ae121c8af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>KmsiCheckboxField</value>
      <webElementGuid>c9cce554-b9da-47fd-b4ba-90bde1585c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DontShowAgain</value>
      <webElementGuid>dc06f173-c3fb-458b-a9c9-bcb66a3cbd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d376713b-8253-44ce-b42e-4028907822a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9c9e9a0c-8c2a-4caf-a0cc-9a98b10921d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>ariaLabel: str['STR_Kmsi_DontShowAgain']</value>
      <webElementGuid>4d3b1637-50c2-41a1-b741-dae85fc77aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Don't show this again</value>
      <webElementGuid>8bd3d13f-97a4-418f-b582-c42884928c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KmsiCheckboxField&quot;)</value>
      <webElementGuid>e6ff1947-6a3f-46e7-901c-e929d2d3b631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='KmsiCheckboxField']</value>
      <webElementGuid>f54b893b-8179-43db-98c5-12f9ace49b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox']/div[3]/div/div[2]/div/div[3]/div/div/label/input</value>
      <webElementGuid>f4849e0e-578c-44d6-b1ce-de221f859548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>2d402a56-9ecb-47c1-bc6a-b6a17afcc17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'KmsiCheckboxField' and @name = 'DontShowAgain' and @type = 'checkbox']</value>
      <webElementGuid>cb66bb97-a18a-4d97-9ca4-b28c8bb5b27a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
