<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Delete</name>
   <tag></tag>
   <elementGuidId>0ebc3f2a-5e3e-4712-a80f-5ca092cd3e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Ctrl+N'])[1]/following::div[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44adcaee-26a6-44a8-a3e2-68395db68ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>0155eda5-8d16-4e8f-bbd0-3b26bf7a8437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>27b71e30-ec67-4b45-b556-776d0021ac46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>c21f851c-2051-4a77-9eaf-30f2c44a5c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex min-w-fit flex-1 cursor-pointer select-none space-x-[18px] rounded-[5px] px-[12px] py-[10px] outline-none bg-blue-500/10</value>
      <webElementGuid>4d4bb233-5426-4383-8cfe-b8841a2a1038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2859fe2a-2505-4dc8-9618-015029587318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>33d79b3d-bc51-42df-979e-5a05e7e96ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;rounded-[8px] border border-neutral-300 bg-white drop-shadow&quot;]/div[@class=&quot;flex flex-col p-[6px] outline-none&quot;]/div[@class=&quot;flex min-w-fit flex-1 cursor-pointer select-none space-x-[18px] rounded-[5px] px-[12px] py-[10px] outline-none bg-blue-500/10&quot;]</value>
      <webElementGuid>a97967cf-6350-49cd-838a-ee85bcf87925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ctrl+N'])[1]/following::div[7]</value>
      <webElementGuid>35cd96ce-84bd-46c8-ae33-8171fac554a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[19]</value>
      <webElementGuid>a7fd712e-c5f9-440a-a099-77981dc3f64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning'])[1]/preceding::div[5]</value>
      <webElementGuid>6897b2a2-178d-4ded-b076-3c8edc87c8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[8]</value>
      <webElementGuid>ebe75dda-f1b6-45ce-83c1-dff733a668ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]</value>
      <webElementGuid>0687e3b2-37ab-412e-8f4e-587eabfb397d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>3ef12c13-cd7b-4732-979c-54dff0f6fbfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
