<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CUST PO_outline-none ease-in-out flex s_b28eec</name>
   <tag></tag>
   <elementGuidId>efd792ad-d6db-4df1-868c-d20d244df5e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/table/tbody/tr/td/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0723a27-9bf8-4097-94eb-d0e59e239340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none ease-in-out flex size-5 flex-shrink-0 items-center justify-center rounded border bg-transparent transition group-pressed:[--color:theme(colors.neutral.700)] border-[--color] [--color:theme(colors.neutral.700)] ring ring-neutral-main/40</value>
      <webElementGuid>444c1d19-24d2-4c3d-8457-c9acb6b4cd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex size-full min-h-screen flex-col bg-neutral-100&quot;]/div[@class=&quot;flex flex-1 flex-col items-stretch justify-center md:flex-row&quot;]/div[@class=&quot;flex w-full max-w-[1650px] flex-1 flex-col px-[10px] py-[30px]&quot;]/div[@class=&quot;mt-6 w-full overflow-x-auto rounded-2xl border bg-white px-[20px] py-6 shadow&quot;]/div[@class=&quot;flex flex-1 flex-col&quot;]/table[@class=&quot;w-full&quot;]/tbody[1]/tr[@class=&quot;last:border-b-none group min-h-[55px] border-b outline-none duration-75 hover:bg-blue-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-blue-600 border-blue-600 bg-blue-50&quot;]/td[@class=&quot;relative h-full min-h-[55px] items-center py-[5px] text-start font-normal px-2&quot;]/div[@class=&quot;flex flex-row items-center&quot;]/label[@class=&quot;group flex items-center gap-2 text-sm transition text-gray-800&quot;]/div[@class=&quot;outline-none ease-in-out flex size-5 flex-shrink-0 items-center justify-center rounded border bg-transparent transition group-pressed:[--color:theme(colors.neutral.700)] border-[--color] [--color:theme(colors.neutral.700)] ring ring-neutral-main/40&quot;]</value>
      <webElementGuid>4abf1349-1a26-463c-9772-ef0bc521ebdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/table/tbody/tr/td/div/label/div</value>
      <webElementGuid>badbf4a7-e11a-43d8-852f-ae315f54bf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUST PO #'])[1]/following::div[2]</value>
      <webElementGuid>13809c1d-ed74-4ce6-9930-b1a28c8a8a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROD #'])[1]/following::div[2]</value>
      <webElementGuid>d239672a-a9ff-4b07-b43a-4fdabd27ce12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/preceding::div[1]</value>
      <webElementGuid>4e12b88d-f3b3-4cf4-a7f5-fed39d358fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[2]/preceding::div[1]</value>
      <webElementGuid>0ab657ae-2272-4ff9-8865-8591c3559b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>4de52818-69e3-4964-98d2-11b0643933d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
