<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>420af158-53f9-4f7f-937e-3b513da6539f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idBtn_Back > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='idBtn_Back']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cee47f72-d22f-4dcb-b837-f62536e3f06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2768032a-4171-4e04-bf9c-33113375e251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pngsrc</name>
      <type>Main</type>
      <value>https://aadcdn.msauth.net/shared/1.0/content/images/arrow_left_d1229aefd268f350621d48f094122f69.png</value>
      <webElementGuid>63b32eb6-5fef-4708-8774-32928bfb8d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svgsrc</name>
      <type>Main</type>
      <value>https://aadcdn.msauth.net/shared/1.0/content/images/arrow_left_43280e0ba671a1d8b5e34f1931c4fe4b.svg</value>
      <webElementGuid>64bdc9ae-81fd-4020-b33d-9799ac03ad8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>imgSrc</value>
      <webElementGuid>d289859f-7edb-49c6-94f8-54f53aa44d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://aadcdn.msauth.net/shared/1.0/content/images/arrow_left_43280e0ba671a1d8b5e34f1931c4fe4b.svg</value>
      <webElementGuid>83e447a2-59e7-4e02-b6fc-2795b97ee582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idBtn_Back&quot;)/img[1]</value>
      <webElementGuid>d4983b23-2bc3-466f-be23-118c4d34821c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='idBtn_Back']/img</value>
      <webElementGuid>dc60874f-e3e1-485d-abab-7372108b5b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://aadcdn.msauth.net/shared/1.0/content/images/arrow_left_43280e0ba671a1d8b5e34f1931c4fe4b.svg')]</value>
      <webElementGuid>bc6c8cfd-c6c6-44f6-bf75-e49fa9585098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>792e3656-d417-4fcf-be36-365ce56734d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://aadcdn.msauth.net/shared/1.0/content/images/arrow_left_43280e0ba671a1d8b5e34f1931c4fe4b.svg']</value>
      <webElementGuid>72a633ff-cf6a-4f96-b8fe-325d2fb03665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
