<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lhander Pangan_grafana-iframe</name>
   <tag></tag>
   <elementGuidId>64e100ff-d569-40e5-af14-316331c21c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.grafana-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fbda547b-2fec-4b28-835f-8cb61550d03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grafana-iframe</value>
      <webElementGuid>430baf5b-572f-49de-8d4c-f97cf08faf7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Grafana Dashboard</value>
      <webElementGuid>9c3e5e2f-ae5f-4e6b-b187-72eaa42f2d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c62ff58d-1c1e-4276-93e5-6edc38d5cebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>2b718c49-b48e-4689-a4ee-0bdf4bae44fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://display.prod.porterpipe.com/d/a6c9d560-ec29-4c54-872b-cf164f310b5d/marketing-dashboard?orgId=1&amp;from=now-7d&amp;to=now&amp;kiosk&amp;theme=light</value>
      <webElementGuid>19e0ba94-fca4-41dd-a410-bc4e8b77ead6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>983cd8ee-a7e6-44fa-9d0b-d779b1cc49fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;flex h-full min-h-screen grow flex-col&quot;]/div[@class=&quot;flex size-full grow flex-col&quot;]/div[@class=&quot;flex h-[calc(100vh-65px)] w-full flex-1&quot;]/iframe[@class=&quot;grafana-iframe&quot;]</value>
      <webElementGuid>871fdbc2-833b-479d-95c4-85c7a61dea05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/iframe</value>
      <webElementGuid>3fbb0282-1ad4-4896-9de4-556984898524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>084da316-5e35-432c-a32f-854f701cb9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Grafana Dashboard' and @src = 'https://display.prod.porterpipe.com/d/a6c9d560-ec29-4c54-872b-cf164f310b5d/marketing-dashboard?orgId=1&amp;from=now-7d&amp;to=now&amp;kiosk&amp;theme=light']</value>
      <webElementGuid>4fa57c94-9b8c-49b4-a5ba-765f9a9f38fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
