<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Okay</name>
   <tag></tag>
   <elementGuidId>0349d2f1-3f7b-4f96-96d5-46c30f0c71ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div/section/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf951ea2-9cd1-46ac-85bd-8e6ff5a992f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b91325d-166d-4677-a3b1-4d1421cbeb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group flex select-none items-center justify-center text-nowrap rounded-[8px] border border-solid border-[--color] text-center outline-none transition ease-in-out focus:border-[--dark-color] focus:shadow-[0_0_0_3px] [--color:theme(colors.blue.600)] [--dark-color:theme(colors.blue.800)] focus:shadow-blue-600/40 bg-[--color] text-white hover:border-[--dark-color] hover:bg-[--dark-color] focus:bg-[--dark-color] data-[selected=&quot;true&quot;]:border-[--dark-color] data-[selected=&quot;true&quot;]:bg-[--dark-color] px-[8px] py-[3px] font-normal</value>
      <webElementGuid>d8ab7cb0-7e91-4dee-a8b9-deeb13b39410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fe3a31e2-225e-4d6a-9d72-75d551fedfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4eedd6cb-dbfb-4bed-a7f4-2022435af6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Okay</value>
      <webElementGuid>80f4d76c-ff54-45fd-8d53-4b218df29248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;fixed inset-0 z-[100000] flex min-h-full items-center justify-center overflow-y-auto bg-black/60 p-4 text-center&quot;]/div[@class=&quot;flex overflow-hidden rounded-[15px] bg-white text-left align-middle shadow-xl outline-none&quot;]/section[@class=&quot;flex size-full flex-col outline-none&quot;]/div[@class=&quot;flex flex-row items-center justify-end space-x-2 border-t border-neutral-300 px-[16px] pb-[8px] pt-[5px]&quot;]/button[@class=&quot;group flex select-none items-center justify-center text-nowrap rounded-[8px] border border-solid border-[--color] text-center outline-none transition ease-in-out focus:border-[--dark-color] focus:shadow-[0_0_0_3px] [--color:theme(colors.blue.600)] [--dark-color:theme(colors.blue.800)] focus:shadow-blue-600/40 bg-[--color] text-white hover:border-[--dark-color] hover:bg-[--dark-color] focus:bg-[--dark-color] data-[selected=&quot;true&quot;]:border-[--dark-color] data-[selected=&quot;true&quot;]:bg-[--dark-color] px-[8px] py-[3px] font-normal&quot;]</value>
      <webElementGuid>e82a7260-c545-44af-b98f-ecb130789d77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[47]</value>
      <webElementGuid>3da1b6bf-d967-49ed-bf59-819e010e6b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>0989055c-4a82-4f76-b5f0-2fe5b2c55c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning'])[1]/following::button[2]</value>
      <webElementGuid>029f5d92-b343-4629-88af-1dffccf87b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Okay']/parent::*</value>
      <webElementGuid>6fe7852d-c253-48c5-a8b2-b64ef88eaf1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>978b1d67-a92c-4a39-9352-06067b424790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Okay' or . = 'Okay')]</value>
      <webElementGuid>70489fb0-bab9-4119-90dc-b2e84f0cd0a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
